# Generated by Django 5.0.4 on 2024-05-18 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrameTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('api_service', models.URLField()),
                ('topics', models.TextField(help_text='Comma-sperated list of topcis')),
                ('matte_options', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UnsplashModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('url', models.URLField()),
                ('oauth_token', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('downloaded_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('tv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='surfer.frametv')),
            ],
        ),
    ]
