# Generated by Django 5.0.4 on 2024-05-18 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frametv',
            name='api_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_service', to='surfer.unsplashmodel'),
        ),
    ]
