# Generated by Django 5.0.4 on 2024-05-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfer', '0002_alter_frametv_api_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frametv',
            name='topics',
            field=models.TextField(blank=True, help_text='Comma-sperated list of topcis', null=True),
        ),
    ]
